spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ee?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 1
#jms
  activemq:
    broker-url: tcp://localhost:61616
    queue: bankMessages

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??sql