spring:
  activemq:
    broker-url: tcp://localhost:61616
    queue: bankMessages

  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      password: 1234

  devtools:
    restart:
      enabled: true
      additional-exclude: src/main/java #重启目录
      additional-include: static/** #classpath下 static修改不重启

  #@Async异步线程池
  task:
    execution:
      pool:
        max-size: 16
        queue-capacity: 1000
        keep-alive: 60s

  mail:
    host: smtp.qq.com
    port: 465
    username: #@qq.com
    password: #
    default-encoding: UTF-8
    default-reply-to: #@qq.com
    properties:
      mail:
        smtp:
          auth: true
          from: #@qq.com
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    protocol: smtp


server:
  port: 8081

logging:
  level:
    root: info
  file:
    path: bank_consumer/logs/

